### ISSUE TITLE
FLStudio manifest is out of date

### ISSUE THREAD

**Issue by AtHeartEngineer** [bottlesdevs/programs#192]
flstudio_win64_20.9.2.2963.exe is no longer the latest version and the checksum is wrong so it won't install

**Comment by mainrs** [comment]
This has been updated. However, the new Fl Studio version does not launch on my machine. Any way to get more detailed logs for this so I can post them? Pinging @sudokit, since they updated the installation manifest.

**Comment by sudokit** [comment]
I wasn't sure which checksum it was but it looked similar to a md5 checksum so i used that. i couldn't find anywhere which checksum should be used. And the out of date issue, just make a pull request to update it. I can try doing it when i have some time.

**Comment by thunze** [comment]
> This has been updated. However, the new Fl Studio version does not launch on my machine. Any way to get more detailed logs for this so I can post them? Pinging @sudokit, since they updated the installation manifest.

FL Studio doesn't launch because the application path provided in the manifest is wrong (should be `.../FL Studio 21/FL64.exe` instead of `.../FL Studio 20/FL64.exe` for FL Studio 21). I submitted #269 to fix this.

Also, the checksums are indeed MD5 as documented [here](https://maintainers.usebottles.com/dependencies/structure/Actions#title4). Hope this helps!
