### ISSUE TITLE
[Bug]: Unable to download the EGS installer through the installers section

### ISSUE THREAD

**Issue by mikefragg** [bottlesdevs/programs#212]
### Describe the bug

Displays this message on the gui 
![image](https://user-images.githubusercontent.com/64165497/222976349-551abbac-2d90-481c-b805-ff0bafad914e.png)
and when launched through the terminal:
19:28:13 (ERROR) Failed to download [https://cdn.usebottles.com/programs/EpicGamesLauncherInstaller.msi] 
19:28:13 (ERROR) Failed to download EpicGamesLauncherInstaller.msi, or checksum failed.
It seems that the servers are down? 

### To Reproduce

1. Launch Bottles with: flatpak run com.usebottles.bottles
2. Open a Bottle
3. Go to "Install Programs..."
4. Install Epic Games Store

### Package

Flatpak from Flathub

### Distribution

Happened on arch, vanilla and currently on ubuntu

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-85-05/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-35-generic
Disk:
    Total: 8324980736
    Free: 8324816896
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
19:28:13 (ERROR) Failed to download [https://cdn.usebottles.com/programs/EpicGamesLauncherInstaller.msi] 
19:28:13 (ERROR) Failed to download EpicGamesLauncherInstaller.msi, or checksum failed.
```

**Comment by kahrendsen** [comment]
I'm also having this issue on Bottles 51.5 on the Steam Deck. For the sake of making sure this issue gets indexed by search engines for people facing similar issues, the text of the error is: "Installation Failed! Installer is not well configured.". This happens when trying to use "Install Programs..." to install the Epic Games Store.

It seems that the URL it's trying to connect to, https://cdn.usebottles.com, does not exist right now.

There's a [commit to the manifest ](https://github.com/bottlesdevs/programs/blame/main/Games/epicgamestore.yml#L30) that updates the URL to https://proxy.usebottles.com/redistributable/programs/EpicGamesLauncherInstaller.msi, which does exist and properly downloads the installer. I'm not sure why the latest Bottles doesn't include that change, I'm not familiar enough with how the Bottles Flatpak and this repository interact. Maybe the author of that commit, @francescomasala, knows.

**Comment by Kinsteen** [comment]
It has just been merged, it will be fixed in a short while

**Comment by Kinsteen** [comment]
I just tested and the change has been distributed, it should work now (restart Bottles to be sure)

**Comment by bleonard252** [comment]
The current latest Bottles Flatpak (including beta) does not have the latest update. Beta (51.0) is actually behind stable (51.5), and neither are up to date.

**Comment by Kinsteen** [comment]
The problem seems to be that the mirror at https://cyyz.mirror.usebottles.com is not updated for some reason. @francescomasala ?

**Comment by francescomasala** [comment]
Uhm, I'll check the cron.

I'll keep everyone updated

**Comment by francescomasala** [comment]
Now is fixed!

**Comment by francescomasala** [comment]
Fixed the cron!

keep me updated

**Comment by bleonard252** [comment]
It now seems resolved and working to me.
